### ISSUE TITLE
More consistent and complete tests across all SDKs

### ISSUE THREAD

**Issue by joshuaauerbachwatson** [nimbella/nimbella-sdk-nodejs#8]
Opening here because there is no issue venue that crosses all SDKs.   The issue is not specific to the nodejs SDK.

**Is your feature request related to a problem? Please describe.**
A public contributor wishing to enhance an SDK should have confidence that there are tests sufficient to find obvious regressions.   A public contributor wishing to make a new SDK (a language not yet covered) should be able to jump-start tests by basing them on the tests of other SDKs.   Right now, the present SDK and the php SDK lack tests.  The Python SDK has tests that cover some object storage functionality but none covering key-value store functionality.  

**Describe the solution you'd like:**
At least one SDK should have "plausibly complete" tests.   Other SDKs should have issues suggesting that they be brought into parity with that SDK.

**Describe alternatives you've considered:**
**Additional context:**
I am developing a Swift SDK (https://github.com/nimbella/nimbella-sdk-swift/issues/1).   I will write such tests as I think I need but, as an outside contributor (even though a former Nimbella employee who had the opportunity to do the right thing in the past 😄 ) I am not really worrying about making them plausibly complete nor readily adaptable to other SDKs but perhaps it will provide a starting point.   The tests for the Swift SDK will be written using the XCode testing framework.

**Comment by joshuaauerbachwatson** [comment]
I can see already that providing good SDK tests for key-value (using redis) is tricky.  Nimbella does not make the redis password for the redis instance of the target namespace directly available in client code.   A proper redis test needs to deploy the SDK under test as part of an action and then invoke the action to perform the actual test (the redis password is available inside the action, which is authenticated to the target namespace).    While the Nimbella deployer can be used to deploy actions, the details of how to incorporate the SDK under test will differ by language.   I will find some solution to this problem in Swift.  I don't know exactly how it will apply to the other languages.

**Comment by rabbah** [comment]
To make this independent of the full nimbella stack, an option could be to deploy a redis instance (using docker?) and use that for the SDK test, providing the required environment variable (and invoking the functions directly otherwise).

**Comment by jthomas** [comment]
I'm all in favour of more tests. Most of the SDKs are currently very light in terms of actual code logic - apart from the storage APIs (which should have separate tests) - meaning integration or end-to-end tests as @joshuaauerbachwatson proposes make most sense. One solution would be to have a set of test projects that use the external SDK APIs that are deployed and tested using bats - like we do in other projects.

**Comment by joshuaauerbachwatson** [comment]
> To make this independent of the full nimbella stack ...

How important is that?   As a developer I have no problem assuming that I should maintain a Nimbella account and use my Nimbella namespace for running tests.

> ... an option could be to deploy a redis instance (using docker?) and use that for the SDK test, providing the required environment variable (and invoking the functions directly otherwise).

Not sure why this is better than using an action.   Note that I do _not_ currently have a docker installation on my laptop, nor any local redis server.   Of course if the only way to run redis tests was to install redis locally or grab a docker image that has it installed, requiring me to re-install docker, I'd bite the bullet and do it but ...

If each SDK, as part of its `tests` area, has a Nimbella project to install the latest build of itself as a dependency of some actions that are also in the `tests` area, then the tests can be automated as a deploy-then-run sequence (I think that's basically what @jthomas suggested above).  

Of course I recognize that debugging remote actions is harder than debugging local code.   But, the improvement by making test "standalone" is only relative, since there is still communication with a redis server (whether locally installed or not, it's still kind of a. black box).   And, by using the "real" redis instances in the Nimbella cloud the communication is more realistic and you have the ability to use `nim kv` commands to make the post-mortem investigation easier.

**Comment by joshuaauerbachwatson** [comment]
Having thought about this some more (and done a few experiments in the context of my nascent Swift SDK) I am coming around to the @rabbah suggestion of writing true unit tests (not requiring remote deployment), reserving the other idea for later integration testing.    Basically, a local redis instance increases the "getting started" overhead (compared to just having a Nimbella account), but then pays dividends in rapid iteration and debugging during development.  Redis clients (e.g. `redistack` for Swift) supply tests and these in turn provide good clues on how to write similar tests that include the Nimbella SDK auth logic.   They do assume a local redis installation but are not dependent on docker, as it turns out.   Installing redis locally seems like it ought to be easy (will find out).

I'll do any further work on this under https://github.com/nimbella/nimbella-sdk-swift/issues/1 as I don't plan to address other SDKs myself.
